networks:
  shared-network:
    external: true

services:
  node-app:
    image: node-app
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - shared-network

  # nginx-stream:
  #   image: nginx:latest
  #   container_name: nginx-stream
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - shared-network
  #   depends_on:
  #     - node-app
