services:
  redis-container:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - stream-network

  node-app:
    image: node-app
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - redis-container
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT} 
    networks:
      - stream-network

  nginx-stream:
    image: nginx:latest
    container_name: nginx-stream
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - stream-network
    depends_on:
      - node-app

networks:
  stream-network:
    driver: bridge